### ISSUE TITLE
Music is "empty" when using two different apps

### ISSUE THREAD

**Issue by Robin-Sch** [kotontrion/dotfiles#9] opened 2024-03-16 17:52 UTC
**Describe the bug**
The music title/app isn't updating

**To Reproduce**
1. Open your browser
2. Play a video/music from for example youtube
3. Stop playing (but don't close the browser, you can close the tab tho)
4. Open spotify or whatever
5. Play a song

**Expected behavior**
It should show the song which is playing, instead of an empty string

**Screenshots**
![image](https://github.com/kotontrion/dotfiles/assets/46354497/9f0da47b-294b-451b-a1ad-2c9dd133a838)
![image](https://github.com/kotontrion/dotfiles/assets/46354497/28a0c467-fe53-4fed-9525-2a33e9e3bb69)

**additional information:**
 - ags: 1.8.0

**Comment by kotontrion** [comment] 2024-03-17 08:19
I could not replicate this using Firefox. Maybe it's Braves mpris implementation.

what's the output of `playerctl -a metadata`in this situation?

**Comment by Robin-Sch** [comment] 2024-03-17 11:54
Yep, firefox is working fine for me too.

Playing youtube:
```
brave mpris:length              50400107331
brave mpris:trackid             '/com/brave/MediaPlayer2/TrackList/TrackB59B1705C548704A1B50BBDF9DCD2028'
brave xesam:album
brave xesam:artist              Lofi Girl
brave xesam:title               lofi hip hop radio 📚 - beats to relax/study to
```

Playing nothing (but the bar says "-"):
```
No player could handle this command
```

**Comment by kotontrion** [comment] 2024-03-17 13:10
looked into this. The issue is that brave does not close its mpris player when you close the youtube tab.
I fixed this by filtering out the stopped players in the bar module, so it will only show playing and paused players. brave will still show up in the sidebar though.

**Closed as completed** 2024-03-18 08:08 UTC
Labels: bug
